#version: '3.8'

#services:
#  db:
#    image: postgres:15
#    restart: always
#    environment:
#      POSTGRES_DB: mydatabase
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#    ports:
#      - "5436:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data:


#version: '3.8'
#
services:
  my_postgres_db:
    image: postgres:15
    container_name: bagstore-postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5436:5432"
    volumes:
#      - postgres_data:/var/lib/postgresql/data
    - ./internal/db/migrations:/app/internal/db/migrations
  app:
    depends_on:
      - my_postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bagstore-app
    ports:
      - "8082:8082"
    environment:
      DB_HOST: my_postgres_db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    restart: always

#  app:
#    depends_on:
#      - my_postgres_db
#    build:
#      context: .
#      dockerfile: Dockerfile
#
#    container_name: bagstore-app
#    ports:
#      - "8082:8082"
##    env_file:
##      - .env
#    environment:
#      DB_HOST: my_postgres_db
#      DB_PORT: 5432
#      DB_USER: myuser
#      DB_PASSWORD: mypassword
#      DB_NAME: mydatabase
#
#    restart: always
#
#volumes:
#  postgres_data:


